from __future__ import annotations

import argparse
import copy
import json
import random
from pathlib import Path

import pandas as pd

from tutorial_scenarios.multi_agent_scenario.main_greedy import (
    Infrastructure,
    Simulation,
    clone_application_definition,
    mec_worker_nodes,
    nearest_worker_node,
    worker_nodes,
)
from tutorial_scenarios.multi_agent_scenario.main_random import (
    CircularReplicaRouting,
    deploy_random_replicas,
)


def parse_args() -> argparse.Namespace:
    scenario_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Generate a Markdown report with deployment placement costs for random and greedy scenarios."
    )
    parser.add_argument(
        "--scenario-dir",
        type=Path,
        default=scenario_dir,
        help="Scenario directory containing topology/services definitions.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=scenario_dir / "results_multi_agent" / "deployment_cost_report.md",
        help="Output Markdown report path.",
    )
    parser.add_argument(
        "--multi-placement-snapshot",
        type=Path,
        default=scenario_dir / "results_multi_agent" / "final_placements.json",
        help="Path to the final placement snapshot generated by main_multi_agent.py.",
    )
    parser.add_argument("--seed", type=int, default=2026, help="Deterministic seed used by both scenarios.")
    parser.add_argument("--replica-count", type=int, default=20, help="Replica count used in the random scenario.")
    parser.add_argument("--activation-count", type=int, default=20, help="Number of user-burst activations.")
    parser.add_argument("--users-per-activation", type=int, default=10, help="Users created per activation.")
    return parser.parse_args()


def fmt_float(value: float) -> str:
    return f"{float(value):.4f}"


def render_markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    header_line = "| " + " | ".join(headers) + " |"
    separator_line = "| " + " | ".join(["---"] * len(headers)) + " |"
    body_lines = ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join([header_line, separator_line, *body_lines])


def build_node_metadata(simulation: Simulation) -> dict[str, dict[str, str | float]]:
    metadata: dict[str, dict[str, str | float]] = {}
    graph = simulation.infrastructure.topology.G
    for item in simulation.list_nodes():
        node_name = str(item["node"])
        attrs = graph.nodes[node_name]
        metadata[node_name] = {
            "cluster_role": str(item.get("cluster_role", "UNKNOWN")),
            "node_role": str(item.get("node_role", "UNKNOWN")),
            "cost": float(attrs.get("COST", item.get("cost", item.get("COST", 0.0)) or 0.0) or 0.0),
        }
    return metadata


def summarize_costs(rows: list[dict[str, object]]) -> dict[str, pd.DataFrame | float | int]:
    frame = pd.DataFrame(rows)
    if frame.empty:
        empty = pd.DataFrame()
        return {
            "total_cost": 0.0,
            "deployments": 0,
            "per_app": empty,
            "per_cluster": empty,
            "per_node": empty,
            "raw": frame,
        }

    per_app = (
        frame.groupby("base_app", dropna=False)
        .agg(
            deployments=("module", "count"),
            unique_apps=("app", "nunique"),
            total_cost=("node_cost", "sum"),
            mean_node_cost=("node_cost", "mean"),
        )
        .reset_index()
        .sort_values(["total_cost", "deployments", "base_app"], ascending=[False, False, True])
    )

    per_cluster = (
        frame.groupby("cluster_role", dropna=False)
        .agg(
            deployments=("module", "count"),
            total_cost=("node_cost", "sum"),
            mean_node_cost=("node_cost", "mean"),
        )
        .reset_index()
        .sort_values(["total_cost", "deployments", "cluster_role"], ascending=[False, False, True])
    )

    per_node = (
        frame.groupby(["node", "cluster_role"], dropna=False)
        .agg(
            deployments=("module", "count"),
            total_cost=("node_cost", "sum"),
        )
        .reset_index()
        .sort_values(["total_cost", "deployments", "node"], ascending=[False, False, True])
    )

    return {
        "total_cost": float(frame["node_cost"].sum()),
        "deployments": int(len(frame)),
        "per_app": per_app,
        "per_cluster": per_cluster,
        "per_node": per_node,
        "raw": frame,
    }


def load_multi_agent_deployments(snapshot_path: Path) -> list[dict[str, object]]:
    path = snapshot_path.expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(
            f"Multi-agent placement snapshot not found: {path}. "
            "Run main_multi_agent.py to generate final_placements.json."
        )
    payload = json.loads(path.read_text(encoding="utf-8"))
    rows: list[dict[str, object]] = []
    for item in payload:
        rows.append(
            {
                "scenario": "Multi-Agent",
                "app": str(item["app"]),
                "base_app": str(item.get("base_app", str(item["app"]).split("::")[0])),
                "module": str(item["vnf"]),
                "node": str(item["node"]),
                "cluster_role": str(item.get("cluster_role", "UNKNOWN")),
                "node_cost": float(item.get("node_cost", 0.0) or 0.0),
            }
        )
    return rows


def reconstruct_random_deployments(
    *,
    scenario_dir: Path,
    seed: int,
    replica_count: int,
) -> list[dict[str, object]]:
    infrastructure = Infrastructure(
        path_to_lab_scenario=scenario_dir,
        results_path=scenario_dir / "tmp_costs_random",
        placement_definition_path="empty_placements.json",
        users_definition_path="empty_users.json",
    )
    infrastructure.routing = CircularReplicaRouting()
    simulation = Simulation(infrastructure=infrastructure, seed=seed)
    node_metadata = build_node_metadata(simulation)
    app_refs = [item.get("id", item["name"]) for item in infrastructure.service_definitions_data]
    deployments = deploy_random_replicas(
        simulation,
        app_refs=app_refs,
        replica_count=replica_count,
        seed=seed,
    )

    rows: list[dict[str, object]] = []
    for deployment in deployments:
        app_name = str(deployment["app"])
        for item in deployment.get("placements", []):
            node_name = str(item["node"])
            metadata = node_metadata[node_name]
            rows.append(
                {
                    "scenario": "Random",
                    "app": app_name,
                    "base_app": app_name.split("::")[0],
                    "module": str(item["vnf"]),
                    "node": node_name,
                    "cluster_role": str(metadata["cluster_role"]),
                    "node_cost": float(metadata["cost"]),
                }
            )
    return rows


def reconstruct_greedy_deployments(
    *,
    scenario_dir: Path,
    seed: int,
    activation_count: int,
    users_per_activation: int,
) -> list[dict[str, object]]:
    infrastructure = Infrastructure(
        path_to_lab_scenario=scenario_dir,
        results_path=scenario_dir / "tmp_costs_greedy",
        placement_definition_path="empty_placements.json",
        users_definition_path="empty_users.json",
    )
    simulation = Simulation(infrastructure=infrastructure, seed=seed)
    node_metadata = build_node_metadata(simulation)
    deployment_nodes = worker_nodes(simulation)
    user_nodes = mec_worker_nodes(simulation)
    app_templates = [copy.deepcopy(item) for item in infrastructure.service_definitions_data]
    rng = random.Random(seed)

    rows: list[dict[str, object]] = []
    instance_counter = 0
    total_users = activation_count * users_per_activation

    for _ in range(total_users):
        template = copy.deepcopy(rng.choice(app_templates))
        base_name = str(template["name"])
        instance_counter += 1
        instance_tag = f"appinst{instance_counter:04d}"

        user_node = rng.choice(user_nodes)
        deployment_node = nearest_worker_node(
            simulation,
            source_node=user_node,
            candidate_nodes=deployment_nodes,
        )

        app_definition, _ = clone_application_definition(template, instance_tag=instance_tag)
        app_ref = app_definition["id"]
        simulation.create_application(app_definition)
        placement_definition = {
            "initialAllocation": [
                {
                    "app": app_ref,
                    "module_name": module["name"],
                    "id_resource": deployment_node,
                }
                for module in app_definition.get("module", [])
            ]
        }
        summary = simulation.deploy_application_vnfs(app_ref, placement_definition)
        metadata = node_metadata[deployment_node]
        for item in summary.get("created", []):
            rows.append(
                {
                    "scenario": "Greedy",
                    "app": str(summary["app"]),
                    "base_app": base_name,
                    "module": str(item["vnf"]),
                    "node": deployment_node,
                    "cluster_role": str(metadata["cluster_role"]),
                    "node_cost": float(metadata["cost"]),
                }
            )
    return rows


def load_cost_model(topology_path: Path) -> str:
    payload = json.loads(topology_path.read_text(encoding="utf-8"))
    rows: list[list[str]] = []
    seen: set[tuple[str, str, float]] = set()
    for cluster in payload.get("clusters", []):
        cluster_role = str(cluster.get("role"))
        for node in cluster.get("nodes", []):
            row = (cluster_role, str(node.get("role")), float(node.get("COST", 0.0) or 0.0))
            if row in seen:
                continue
            seen.add(row)
            rows.append([row[0], row[1], fmt_float(row[2])])
    rows.sort(key=lambda item: (item[0], item[1]))
    return render_markdown_table(["Cluster role", "Node role", "Cost per deployment"], rows)


def build_report(
    *,
    topology_path: Path,
    random_summary: dict,
    greedy_summary: dict,
    multi_summary: dict,
) -> str:
    summary_table = render_markdown_table(
        ["Metric", "Random", "Greedy", "Multi-Agent"],
        [
            [
                "Deployments",
                str(random_summary["deployments"]),
                str(greedy_summary["deployments"]),
                str(multi_summary["deployments"]),
            ],
            [
                "Total placement cost",
                fmt_float(random_summary["total_cost"]),
                fmt_float(greedy_summary["total_cost"]),
                fmt_float(multi_summary["total_cost"]),
            ],
        ],
    )

    per_app_table = render_markdown_table(
        ["Scenario", "Application", "Deployments", "Unique apps", "Total cost", "Mean node cost"],
        [
            [
                scenario_name,
                str(row["base_app"]),
                str(int(row["deployments"])),
                str(int(row["unique_apps"])),
                fmt_float(row["total_cost"]),
                fmt_float(row["mean_node_cost"]),
            ]
            for scenario_name, summary in (
                ("Random", random_summary),
                ("Greedy", greedy_summary),
                ("Multi-Agent", multi_summary),
            )
            for _, row in summary["per_app"].iterrows()
        ],
    )

    per_cluster_table = render_markdown_table(
        ["Scenario", "Cluster type", "Deployments", "Total cost", "Mean node cost"],
        [
            [
                scenario_name,
                str(row["cluster_role"]),
                str(int(row["deployments"])),
                fmt_float(row["total_cost"]),
                fmt_float(row["mean_node_cost"]),
            ]
            for scenario_name, summary in (
                ("Random", random_summary),
                ("Greedy", greedy_summary),
                ("Multi-Agent", multi_summary),
            )
            for _, row in summary["per_cluster"].iterrows()
        ],
    )

    top_nodes_table = render_markdown_table(
        ["Scenario", "Node", "Cluster type", "Deployments", "Total cost"],
        [
            [
                scenario_name,
                str(row["node"]),
                str(row["cluster_role"]),
                str(int(row["deployments"])),
                fmt_float(row["total_cost"]),
            ]
            for scenario_name, summary in (
                ("Random", random_summary),
                ("Greedy", greedy_summary),
                ("Multi-Agent", multi_summary),
            )
            for _, row in summary["per_node"].head(10).iterrows()
        ],
    )

    return "\n".join(
        [
            "# Deployment Cost Report",
            "",
            "## Cost Model",
            "",
            load_cost_model(topology_path),
            "",
            "Assumption: the intended high-cost edge tier is `MEC` (interpreting the request as `CDC` very cheap, `EDC` medium, `MEC` highly costly).",
            "",
            "## Summary",
            "",
            summary_table,
            "",
            "## Cost by Application",
            "",
            per_app_table,
            "",
            "## Cost by Cluster Type",
            "",
            per_cluster_table,
            "",
            "## Top Cost Nodes",
            "",
            top_nodes_table,
            "",
        ]
    )


def main() -> None:
    args = parse_args()
    scenario_dir = args.scenario_dir.resolve()
    topology_path = scenario_dir / "topology.json"

    random_rows = reconstruct_random_deployments(
        scenario_dir=scenario_dir,
        seed=int(args.seed),
        replica_count=int(args.replica_count),
    )
    greedy_rows = reconstruct_greedy_deployments(
        scenario_dir=scenario_dir,
        seed=int(args.seed),
        activation_count=int(args.activation_count),
        users_per_activation=int(args.users_per_activation),
    )
    multi_rows = load_multi_agent_deployments(args.multi_placement_snapshot)

    random_summary = summarize_costs(random_rows)
    greedy_summary = summarize_costs(greedy_rows)
    multi_summary = summarize_costs(multi_rows)
    report = build_report(
        topology_path=topology_path,
        random_summary=random_summary,
        greedy_summary=greedy_summary,
        multi_summary=multi_summary,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
